name: Build and deploy to gh-pages

on: push

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "pnpm"
      - run: sudo apt-get update -yy && sudo apt-get install -yy webp
      - run: pnpm install
      - run: pnpm run build
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy to gh-pages
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
