name: Build and deploy to gh-pages

on: push

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          runtime: node@24
          cache: true
          require-lockfile: true
      - run: sudo apt-get update -yy && sudo apt-get install -yy webp
      - run: pnpm run build
      - run: test -s dist/bundle.js
      - uses: JamesIves/github-pages-deploy-action@v4.9.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy to gh-pages
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
